<div style="position: relative; width: 100%; height: 100vh; padding: 50px; box-sizing: border-box;">
    <!-- Logo positioned in the right corner -->
    <img src="logo.png" style="position: absolute; top: 10px; right: 10px; width: 200px;"/>

   <!-- Proprietary Content -->
   <div style="position: absolute; bottom: px5; left: 5%; transform: translateX(-50%); color: grey; text-align: left;font-style: italic">
   <p>Proprietary content. © 10xTechClub. All Rights Reserved. Unauthorized use or distribution prohibited.</p>
   </div>
</div>

## <span style="color:green">Intorduction to Numpy

### <span style="color:blue">What is NumPy?
    
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

### <span style="color:blue">Why Use NumPy?
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

### <span style="color:blue">Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

### <span style="color:blue">Installation of NumPy
If you have Python and PIP already installed on a system, then installation of NumPy is very easy.

Install it using this command:

In [19]:
!pip install numpy

### <span style="color:blue">NumPy as np
NumPy is usually imported under the np alias.

- alias: In Python alias are an alternate name for referring to the same thing.

Create an alias with the as keyword while importing:

In [20]:
import numpy as np

### <span style="color:blue">Creating Arrays
Arrays in NumPy are created using the np.array() function. They can be 1-dimensional, 2-dimensional, or 3-dimensional.

In [21]:
import numpy as np

# 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(array_1d)

# 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:")
print(array_2d)

# 3D array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Array:")
print(array_3d)


1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]]

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### <span style="color:blue">Accessing Items from the Array
Items in arrays can be accessed using indices.

In [22]:
print("\nAccessing Items:")
print(array_1d[0])  # First element in 1D array
print(array_2d[0, 1])  # Second element in the first row of 2D array
print(array_3d[1, 0, 1])  # Second element in the first sub-array of the second array in 3D array



Accessing Items:
1
2
6


### <span style="color:blue">Creating Array of 1s and 0s
np.ones() and np.zeros() functions are used to create arrays of ones and zeros respectively.

In [23]:
array_ones = np.ones((3, 3))
print("\nArray of Ones:")
print(array_ones)

array_zeros = np.zeros((2, 2))
print("\nArray of Zeros:")
print(array_zeros)



Array of Ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array of Zeros:
[[0. 0.]
 [0. 0.]]


### <span style="color:blue">Slicing
Slicing is used to access a range of elements in arrays.

In [24]:
print("\nSlicing 1D Array:")
print(array_1d[1:4])  # Elements from index 1 to 3

print("\nSlicing 2D Array:")
print(array_2d[:, 1])  # Second column of all rows



Slicing 1D Array:
[2 3 4]

Slicing 2D Array:
[2 5]


### <span style="color:blue">Data Type (dtype)
The dtype attribute gives the data type of elements in the array.

In [25]:
print("\nData Type:")
print(array_1d.dtype)



Data Type:
int32


### <span style="color:blue">Data Type Conversion (astype)
The astype() function is used to convert the data type of an array.

In [26]:
array_float = array_1d.astype(float)
print("\nArray with Float Data Type:")
print(array_float)
print(array_float.dtype)



Array with Float Data Type:
[1. 2. 3. 4. 5.]
float64


### <span style="color:blue">Shape
The shape attribute gives the dimensions of the array.

In [27]:
print("\nShape of 2D Array:")
print(array_2d.shape)



Shape of 2D Array:
(2, 3)


### <span style="color:blue">Reshape
The reshape() function changes the shape of the array without changing its data.



In [28]:
array_reshaped = array_2d.reshape((3, 2))
print("\nReshaped Array:")
print(array_reshaped)



Reshaped Array:
[[1 2]
 [3 4]
 [5 6]]


### <span style="color:blue"> Splitting
Arrays can be split into multiple arrays using np.split() or similar functions.

In [29]:
array_split = np.split(array_2d, 2)
print("\nSplit Array:")
print(array_split)



Split Array:
[array([[1, 2, 3]]), array([[4, 5, 6]])]


### <span style="color:blue">Searching - where()
The np.where() function is used to search for elements that satisfy a condition.

In [30]:
indices = np.where(array_1d > 3)
print("\nIndices of Elements Greater Than 3:")
print(indices)



Indices of Elements Greater Than 3:
(array([3, 4], dtype=int64),)


### <span style="color:blue">Sorting
The sort() function sorts an array.

In [31]:
array_sorted = np.sort(array_1d)
print("\nSorted Array:")
print(array_sorted)



Sorted Array:
[1 2 3 4 5]


### <span style="color:blue">Filtering
Arrays can be filtered based on conditions.

In [32]:
array_filtered = array_1d[array_1d > 3]
print("\nFiltered Array (Elements > 3):")
print(array_filtered)



Filtered Array (Elements > 3):
[4 5]


## <span style="color:blue">Convert Dataset into NumPy array

In [33]:
import numpy as np

# Dataset
data = np.array([
    ["Model S", "Tesla", 2021, 79990, 670],
    ["Corolla", "Toyota", 2020, 20000, 139],
    ["Mustang", "Ford", 2019, 55000, 450],
    ["Civic", "Honda", 2018, 22000, 158],
    ["Camry", "Toyota", 2021, 25000, 203],
    ["3 Series", "BMW", 2020, 41000, 255],
    ["A4", "Audi", 2019, 39000, 248],
    ["Accord", "Honda", 2018, 24000, 192],
    ["Model 3", "Tesla", 2021, 39990, 283],
    ["Altima", "Nissan", 2020, 24000, 188],
    ["C-Class", "Mercedes-Benz", 2020, 41000, 255],
    ["Malibu", "Chevrolet", 2019, 22000, 160],
    ["Impreza", "Subaru", 2018, 19000, 152],
    ["Charger", "Dodge", 2021, 29995, 292],
    ["Escape", "Ford", 2020, 25000, 180],
    ["Highlander", "Toyota", 2021, 35000, 295],
    ["Cherokee", "Jeep", 2019, 27000, 180],
    ["Outback", "Subaru", 2020, 27000, 182],
    ["CX-5", "Mazda", 2021, 26000, 187],
    ["Q5", "Audi", 2021, 44000, 261],
    ["GLC", "Mercedes-Benz", 2020, 43000, 255],
    ["X3", "BMW", 2019, 42000, 248],
    ["Rogue", "Nissan", 2020, 27000, 170],
    ["Tucson", "Hyundai", 2021, 25000, 187],
    ["Forester", "Subaru", 2020, 25000, 182]
])


### <span style="color:blue">Create 1D Array

In [34]:
# 1D array - Extracting years
array_1d = data[:, 2].astype(int)
print("1D Array (Years):")
print(array_1d)


1D Array (Years):
[2021 2020 2019 2018 2021 2020 2019 2018 2021 2020 2020 2019 2018 2021
 2020 2021 2019 2020 2021 2021 2020 2019 2020 2021 2020]


### <span style="color:blue">Create 2D Array

In [35]:
# 2D array - Extracting years and prices
array_2d = data[:, [2, 3]].astype(int)
print("\n2D Array (Years and Prices):")
print(array_2d)



2D Array (Years and Prices):
[[ 2021 79990]
 [ 2020 20000]
 [ 2019 55000]
 [ 2018 22000]
 [ 2021 25000]
 [ 2020 41000]
 [ 2019 39000]
 [ 2018 24000]
 [ 2021 39990]
 [ 2020 24000]
 [ 2020 41000]
 [ 2019 22000]
 [ 2018 19000]
 [ 2021 29995]
 [ 2020 25000]
 [ 2021 35000]
 [ 2019 27000]
 [ 2020 27000]
 [ 2021 26000]
 [ 2021 44000]
 [ 2020 43000]
 [ 2019 42000]
 [ 2020 27000]
 [ 2021 25000]
 [ 2020 25000]]


### <span style="color:blue">Accessing Items from the Array

In [36]:
print("\nAccessing Items:")
print(array_1d[0])  # First element in 1D array
print(array_2d[0, 1])  # Second element in the first row of 2D array


Accessing Items:
2021
79990


### <span style="color:blue">Slicing

In [37]:
print("\nSlicing 1D Array:")
print(array_1d[1:4])  # Elements from index 1 to 3

print("\nSlicing 2D Array:")
print(array_2d[:, 1])  # Second column of all rows



Slicing 1D Array:
[2020 2019 2018]

Slicing 2D Array:
[79990 20000 55000 22000 25000 41000 39000 24000 39990 24000 41000 22000
 19000 29995 25000 35000 27000 27000 26000 44000 43000 42000 27000 25000
 25000]


### <span style="color:blue">Data Type (dtype)

In [38]:
print("\nData Type:")
print(array_1d.dtype)



Data Type:
int32


### <span style="color:blue">Data Type Conversion (astype)

In [39]:
array_float = array_1d.astype(float)
print("\nArray with Float Data Type:")
print(array_float)
print(array_float.dtype)



Array with Float Data Type:
[2021. 2020. 2019. 2018. 2021. 2020. 2019. 2018. 2021. 2020. 2020. 2019.
 2018. 2021. 2020. 2021. 2019. 2020. 2021. 2021. 2020. 2019. 2020. 2021.
 2020.]
float64


### <span style="color:blue">Shape

In [40]:
print("\nShape of 2D Array:")
print(array_2d.shape)



Shape of 2D Array:
(25, 2)


### <span style="color:blue">Reshape

In [41]:
array_reshaped = array_2d.reshape((5,2,5))
print("\nReshaped Array:")
print(array_reshaped)



Reshaped Array:
[[[ 2021 79990  2020 20000  2019]
  [55000  2018 22000  2021 25000]]

 [[ 2020 41000  2019 39000  2018]
  [24000  2021 39990  2020 24000]]

 [[ 2020 41000  2019 22000  2018]
  [19000  2021 29995  2020 25000]]

 [[ 2021 35000  2019 27000  2020]
  [27000  2021 26000  2021 44000]]

 [[ 2020 43000  2019 42000  2020]
  [27000  2021 25000  2020 25000]]]


### <span style="color:blue">Searching - where()

In [42]:
indices = np.where(array_1d > 2020)
print("\nIndices of Elements Greater Than 2020:")
print(indices)



Indices of Elements Greater Than 2020:
(array([ 0,  4,  8, 13, 15, 18, 19, 23], dtype=int64),)


### <span style="color:blue">Sorting

In [43]:
array_sorted = np.sort(array_1d)
print("\nSorted Array:")
print(array_sorted)



Sorted Array:
[2018 2018 2018 2019 2019 2019 2019 2019 2020 2020 2020 2020 2020 2020
 2020 2020 2020 2021 2021 2021 2021 2021 2021 2021 2021]


### <span style="color:blue">Filtering

In [44]:
array_filtered = array_1d[array_1d > 2019]
print("\nFiltered Array (Years > 2019):")
print(array_filtered)



Filtered Array (Years > 2019):
[2021 2020 2021 2020 2021 2020 2020 2021 2020 2021 2020 2021 2021 2020
 2020 2021 2020]


### <span style="color:blue"> Querying the dataframe


In [45]:
# Cars from 2021
cars_2021 = data[data[:, 2].astype(int) == 2021]
print("\nCars from 2021:")
print(cars_2021)
# More dataframe Questions


Cars from 2021:
[['Model S' 'Tesla' '2021' '79990' '670']
 ['Camry' 'Toyota' '2021' '25000' '203']
 ['Model 3' 'Tesla' '2021' '39990' '283']
 ['Charger' 'Dodge' '2021' '29995' '292']
 ['Highlander' 'Toyota' '2021' '35000' '295']
 ['CX-5' 'Mazda' '2021' '26000' '187']
 ['Q5' 'Audi' '2021' '44000' '261']
 ['Tucson' 'Hyundai' '2021' '25000' '187']]


### <span style="color:blue">PRACTICE QUESTIONS

In [ ]:
import pandas as pd

# Load the dataset
df = pd.read_csv('city_information.csv')
print(df.head())

#### <span style="color:red">1.Create a 1D numpy array from the 'Population (millions)' column.

In [ ]:
#import

# Load the dataset

# Convert 'Population (millions)' column to numpy array


#### <span style="color:red">2.Create a 2D numpy array from the 'Population (millions)' and 'Area (sq km)' columns.

In [ ]:
# Convert 'Population (millions)' and 'Area (sq km)' columns to a 2D numpy array




In [ ]:
# Create 2D array from Population and Area columns


#### <span style="color:red">3.Access the first five items of the 'GDP per Capita ($)' array.

In [ ]:
# Convert 'GDP per Capita ($)' column to numpy array

# Access the first five items




#### <span style="color:red">4.Create an array of ones and an array of zeros with the same length as the dataset.

In [ ]:
# Create an array of ones

# Create an array of zeros



#### <span style="color:red">5.Show slicing of the 'Area (sq km)' array to get the last five elements.

In [ ]:
# Convert 'Area (sq km)' column to numpy array

# Slice to get the last five elements





#### <span style="color:red">6.Find the data type of the 'Population (millions)' array and convert it to float.

In [ ]:
# Check the data type of 'Population (millions)' array

# Convert the array to float





#### <span style="color:red">7.Get the shape of the 'Population (millions)' array

In [ ]:
# Get the shape of 'Population (millions)' array



#### <span style="color:red">8.Reshape the 'Population (millions)' array into a 2D array with 3 columns.

In [ ]:
# Reshape the 'Population (millions)' array




#### <span style="color:red">9.Split the 'GDP per Capita ($)' array into 3 equal parts.

In [ ]:
# Split the 'GDP per Capita ($)' array into 3 equal parts


#### <span style="color:red">10.Find the indices of cities with GDP per Capita greater than $50,000.

In [ ]:
# Find indices where GDP per Capita is greater than 50,000



#### <span style="color:Red">11. Sort the 'Population (millions)' array in ascending order.

In [ ]:
# Sort the 'Population (millions)' array



#### <span style="color:Red">12.Filter the 'Area (sq km)' array to show only values greater than 5000.

In [ ]:
# Filter 'Area (sq km)' array to show values greater than 5000


#### <span style="color:red">13.Perform a query to find cities with a population between 5 and 10 million.

In [ ]:
# Perform the query using numpy



#### <span style="color:red"> 14.Find cities with an area greater than 1000 sq km and a GDP per Capita less than $50,000.

In [ ]:
# Perform the query using numpy



#### <span style="color:red">15.Find cities in 'China' with a population greater than 10 million.

In [ ]:
# Convert 'Country' and 'City' columns to numpy arrays


# Perform the query using numpy



#### <span style="color:red">16.Find cities with a population less than 5 million or GDP per Capita greater than $60,000.

In [ ]:
# Perform the query using numpy





#### <span style="color:red">17.Find cities in 'USA' with a GDP per Capita greater than $60,000.

In [ ]:
# Perform the query using numpy



## <span style="color:blue">-----END OF THE SESSION-----

## <span style="color:Red"> ASSIGNMENT

In [ ]:
import pandas as pd
data = pd.read_csv("animal.csv")
print(data.head())

<span style="color:red">1.Convert the dataset into a NumPy array.

<span style="color:red">2. Create 1D and 2D arrays.

<span style="color:red">3. Access items from the array.

<span style="color:red">4. Sort an array in ascending order

<span style="color:red">5. Demonstrate how to slice arrays in NumPy. Extract the first five elements from the animal_arr array and the last five elements from the lifespan_arr array.

<span style="color:red">6. Display the data type of the lifespan_arr array and change its data type to float.

<span style="color:red">7. Display the shape of the lifespan_arr array and reshape it to a 6x5 matrix.

<span style="color:red">8.Find herbivorous animals that are endangered.

<span style="color:red">9. Find animals living in 'Grasslands' with a lifespan less than 20 years.

<span style="color:red">10. Find 'Mammals' that are not endangered

<span style="color:red">11. Find animals living in 'Jungle' with a lifespan between 10 and 30 years.

<span style="color:red">12. Find animals that are either 'Birds' or live in 'Ocean'.

<span style="color:red">13. Find non-endangered animals with a lifespan greater than 30 years.

<div style="position: relative; width: 100%; height: 100vh; padding: 50px; box-sizing: border-box;">
    <!-- Logo positioned in the right corner -->
    <img src="logo.png" style="position: absolute; top: 10px; right: 10px; width: 200px;"/>

   <!-- Proprietary Content -->
   <div style="position: absolute; bottom: px5; left: 5%; transform: translateX(-50%); color: grey; text-align: left;font-style: italic">
   <p>Proprietary content. © 10xTechClub. All Rights Reserved. Unauthorized use or distribution prohibited.</p>
   </div>
</div>